featurey:
  - head-branch: ["^feature/", "^feat/"]

fixy:
  - head-branch: ["^fix/", "^bug/"]

enhancementy:
  - head-branch: ["^enhancement/", "^improvement/"]

refactory:
  - head-branch: ["^refactor/"]

docsy:
  - head-branch: ["^docs/"]

chorey:
  - head-branch: ["^chore/"]