name: PR Labeler

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

jobs:
  pr-labeler:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    uses: dynamic-framework/.github/.github/workflows/pr-labeler.yml@feat/own-workflows-actions
    with:
      configuration-path: .github/labeler.yml