name: PR Labeler

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

jobs:
  pr-labeler:
    uses: dynamic-framework/.github/.github/workflows/pr-labeler.yml@feat/own-workflows-actions
