name: PR Labeler

on:
  pull_request:
    types: [opened]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: PR Labeler
        uses: dynamic-framework/.github/.github/workflows/pr-labeler.yml@feat/own-workflows-actions
