name: Publish page
on:
  release:
    types: [published]

permissions:
  contents: write 

jobs:
  deploy-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: echo "Build your page here, for example: npm run build"

      - name: Deploy page 🚀
        uses: dynamic-framework/.github/.github/actions/push-folder-page@feat/own-workflows-actions
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_folder: docs
          target_branch: docs
          target_folder: custom-docs
          commit_message: 'doc: update doc into custom folder'
          clean: true